### ISSUE TITLE
Support GHC 9.6

### ISSUE THREAD

**Issue by chshersh** [chshersh/iris#116]
The GHC 9.6.1 was released recently and it makes sense to support compilation of `iris` with the new version of the Haskell compiler.

Steps needed to be done:

- [ ] Increase `base` upper bound in `iris.cabal`
    https://github.com/chshersh/iris/blob/e9b6c25df2bf179dc8d9f32f05c55aa8f7febcce/iris.cabal#L29-L30

- [ ] Update the `tested-with` field
    https://github.com/chshersh/iris/blob/e9b6c25df2bf179dc8d9f32f05c55aa8f7febcce/iris.cabal#L19-L23

- [ ] Add new warnings
    https://github.com/chshersh/iris/blob/e9b6c25df2bf179dc8d9f32f05c55aa8f7febcce/iris.cabal#L55-L56

- [ ] Fix all compilation errors and warnings if any

- [ ] Update CI pipelines
    > Refer to the following blog post for guidance around CI:
    > 
    > * [Dead simple cross-platform GitHub Actions for Haskell](https://kodimensional.dev/github-actions)

    https://github.com/chshersh/iris/blob/e9b6c25df2bf179dc8d9f32f05c55aa8f7febcce/.github/workflows/ci.yml#L20-L24

**Comment by celsobonutti** [comment]
I'd like to tackle this one 😊

**Comment by chshersh** [comment]
@celsobonutti Sure, go for it 👍🏻

**Comment by celsobonutti** [comment]
This depends on colourista supporting 9.6, so I’ve created a [PR](https://github.com/kowainik/colourista/pull/97) there.
Once that’s merged, I’ll do the work for this issue.

**Comment by chshersh** [comment]
@celsobonutti Thanks for the heads-up!

I replaced `colourista` with `pretty-terminal` in #118, so `iris` shouldn't be blocked anymore. Feel free to continue the GHC 9.6. support in this repository 🙂

**Comment by celsobonutti** [comment]
Oki doki! Thank you!
