### ISSUE TITLE
Add test for '--version' and '--numeric-version' parser

### ISSUE THREAD

**Issue by chshersh** [chshersh/iris#57]
Similar to #56

Add unit tests for the `--version` and `--numeric-version` options parsing.

**Comment by CThuleHansen** [comment]
I have attempted this in https://github.com/chshersh/iris/pull/71

**Comment by CThuleHansen** [comment]
Pretty sure this can be closed according to https://github.com/chshersh/iris/pull/71

**Comment by chshersh** [comment]
@CThuleHansen Indeed! Thanks for the reminder 🙂
