### ISSUE TITLE
Detect non-interactive terminals automatically

### ISSUE THREAD

**Issue by chshersh** [chshersh/iris#58]
Currently, it's possible to disable interactivity by specifying the `--no-input` options. But some terminals are non-interactive by nature (e.g. on CI). So it would be great to check this and specify the value of `InteractiveMode` automatically.

**Comment by german1608** [comment]
Would checking the [`$-` environment variable](https://stackoverflow.com/questions/42757236/what-does-mean-in-bash) suffice?

**Comment by marcellourbani** [comment]
I believe one should use hSupportsANSI from ansi-terminal

**Comment by marcellourbani** [comment]
will have a go

**Comment by chshersh** [comment]
Checking `$-` is a valid option. But it would be nice to have a cross-platform solution.
