### ISSUE TITLE
Run pre-commit-hooks on CI

### ISSUE THREAD

**Issue by chshersh** [chshersh/iris#78]
To enforce that they're actually used.

**Comment by lejara** [comment]
Hello!

May i work on this?

**Comment by marcellourbani** [comment]
I'll have a go at this

**Comment by chshersh** [comment]
That's a difficult question to answer 😅 

Now I'm not even sure how to do this properly 🤔 In the future, pre-commit hooks will run tools like `hlint` and `fourmolu`. This means, the environment needs to install them somehow and this might be a bit involved.

We also have a job for running HLint on CI so we don't need duplication. Not sure if it makes sense to combine them under the single pre-commit umbrella or keep them separate 🤔  I'd love to avoid job duplication.

**Comment by marcellourbani** [comment]
my understanding is that pre-commit installs the required tools automatically, so that wouldn't be a problem . We might have to create our own plugins if they don't exist already

**Comment by marcellourbani** [comment]
I did consider adding this to say the cabal workflow but would run once per architecture, which seems overkill.
As of pre-commit, my understanding is that to add hlint and formolou in pre-commit is only a matter of setting it in .pre-commit-config.yaml
If you mean running it in regular pre-commit but not in CI, I think it's possible setting separate sections in the same file.

Not too sure, never heard about pre-commit until doing this

**Comment by chshersh** [comment]
I think I'm closing this issue without adding pre-commit hooks to CI with the following reasoning:

* We already have an HLint job on CI. I'd like to avoid job duplication. This means a more complicated `pre-commit` setup.
* I'm not sure pre-commit will install the same HLint version as on CI. And this will become worse for multiple tools. We'll need something like `nix-shell` and use it consistently on both CI and locally to avoid version mismatches. This is going to be a lot of work.
* I see pre-commit mostly as a local dev requirement, not a CI config.
* I mostly want pre-commit for the whitespace check. But it should be resolved after adding `fourmolu` anyway so `pre-commit` won't bring much to the table.

@marcellourbani Thanks for providing all the options and participating in the discussion! It really helped me to understand the desired workflow 🙂
